import { lighten, darken } from 'polished';

export const primaryColor1 = '#111';
export const primaryColor2 = lighten(0.07, primaryColor1);
export const secondaryColor1 = '#999';
export const secondaryColor2 = darken(0.04, secondaryColor1);
export const textColor1 = '#111';
export const textColor2 = lighten(0.1, textColor1);
export const white = '#FFFFFF';
export const borderInAvtiveColor = '#ddd';
export const borderAvtiveColor = '#999';
export const linkColor = '#737373';
export const activeLinkColor = '#191919';
export const dividerColor = '#f1f1f1';
export const inputBgColor = '#f1f1f1';
export const errorColor = '#f44336';
export const warnColor = '#9e9d24';
export const successColor = '#689f38';
export const likeColor = '#f15151';
export const greenColor = '#689f38';
export const iconColor = '#939393';
export const hoverIconColor = '#383838';
export const selectedIconColor = lighten(0.05, primaryColor1);
export const hoverSelectedIconColor = primaryColor1;