// flow-typed signature: e59dbbdbeac5c080c97928b03925c22a
// flow-typed version: <<STUB>>/@types/jest_v^20.0.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
