// flow-typed signature: 7e545291eca1b32ed268936b11e159b8
// flow-typed version: <<STUB>>/@types/jest_v^22.0.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
