// flow-typed signature: a6e0eab497fc5c9e6e830ebc54b8f6fb
// flow-typed version: <<STUB>>/camelcase-keys-deep_v^0.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'camelcase-keys-deep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'camelcase-keys-deep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'camelcase-keys-deep/index' {
  declare module.exports: $Exports<'camelcase-keys-deep'>;
}
declare module 'camelcase-keys-deep/index.js' {
  declare module.exports: $Exports<'camelcase-keys-deep'>;
}
