// flow-typed signature: 6e01980a24f355c1ff0ec78ab035c8e4
// flow-typed version: <<STUB>>/eslint-config-eslint_v^4.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-eslint/index' {
  declare module.exports: $Exports<'eslint-config-eslint'>;
}
declare module 'eslint-config-eslint/index.js' {
  declare module.exports: $Exports<'eslint-config-eslint'>;
}
