// flow-typed signature: b878303a18ae26e0ebbca2d18c796c0f
// flow-typed version: <<STUB>>/jest-styled-components_v^3.3.1/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-styled-components/native/index' {
  declare module.exports: any;
}

declare module 'jest-styled-components/src/index' {
  declare module.exports: any;
}

declare module 'jest-styled-components/src/matchers/toHaveStyleRule' {
  declare module.exports: any;
}

declare module 'jest-styled-components/src/matchers/toHaveStyleRule.native' {
  declare module.exports: any;
}

declare module 'jest-styled-components/src/matchers/toMatchStyledComponentsSnapshot' {
  declare module.exports: any;
}

declare module 'jest-styled-components/src/serializers/styleSheetSerializer' {
  declare module.exports: any;
}

declare module 'jest-styled-components/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-styled-components/native/index.js' {
  declare module.exports: $Exports<'jest-styled-components/native/index'>;
}
declare module 'jest-styled-components/src/index.js' {
  declare module.exports: $Exports<'jest-styled-components/src/index'>;
}
declare module 'jest-styled-components/src/matchers/toHaveStyleRule.js' {
  declare module.exports: $Exports<'jest-styled-components/src/matchers/toHaveStyleRule'>;
}
declare module 'jest-styled-components/src/matchers/toHaveStyleRule.native.js' {
  declare module.exports: $Exports<'jest-styled-components/src/matchers/toHaveStyleRule.native'>;
}
declare module 'jest-styled-components/src/matchers/toMatchStyledComponentsSnapshot.js' {
  declare module.exports: $Exports<'jest-styled-components/src/matchers/toMatchStyledComponentsSnapshot'>;
}
declare module 'jest-styled-components/src/serializers/styleSheetSerializer.js' {
  declare module.exports: $Exports<'jest-styled-components/src/serializers/styleSheetSerializer'>;
}
declare module 'jest-styled-components/src/utils.js' {
  declare module.exports: $Exports<'jest-styled-components/src/utils'>;
}
