// flow-typed signature: 18c75421142cfabb9441d107328550f0
// flow-typed version: <<STUB>>/react-event-listener_v^0.5.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-event-listener'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-event-listener' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-event-listener/dist/react-event-listener.cjs' {
  declare module.exports: any;
}

declare module 'react-event-listener/dist/react-event-listener.umd' {
  declare module.exports: any;
}

declare module 'react-event-listener/src/index' {
  declare module.exports: any;
}

declare module 'react-event-listener/src/supports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-event-listener/dist/react-event-listener.cjs.js' {
  declare module.exports: $Exports<'react-event-listener/dist/react-event-listener.cjs'>;
}
declare module 'react-event-listener/dist/react-event-listener.umd.js' {
  declare module.exports: $Exports<'react-event-listener/dist/react-event-listener.umd'>;
}
declare module 'react-event-listener/src/index.js' {
  declare module.exports: $Exports<'react-event-listener/src/index'>;
}
declare module 'react-event-listener/src/supports.js' {
  declare module.exports: $Exports<'react-event-listener/src/supports'>;
}
