// flow-typed signature: fba9140fac9f0b5129ffda701d737e41
// flow-typed version: <<STUB>>/react-responsive-masonry_v^2.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive-masonry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive-masonry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive-masonry/es/index' {
  declare module.exports: any;
}

declare module 'react-responsive-masonry/es/Masonry/index' {
  declare module.exports: any;
}

declare module 'react-responsive-masonry/es/ResponsiveMasonry/index' {
  declare module.exports: any;
}

declare module 'react-responsive-masonry/lib/index' {
  declare module.exports: any;
}

declare module 'react-responsive-masonry/lib/Masonry/index' {
  declare module.exports: any;
}

declare module 'react-responsive-masonry/lib/ResponsiveMasonry/index' {
  declare module.exports: any;
}

declare module 'react-responsive-masonry/umd/react-responsive-masonry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive-masonry/es/index.js' {
  declare module.exports: $Exports<'react-responsive-masonry/es/index'>;
}
declare module 'react-responsive-masonry/es/Masonry/index.js' {
  declare module.exports: $Exports<'react-responsive-masonry/es/Masonry/index'>;
}
declare module 'react-responsive-masonry/es/ResponsiveMasonry/index.js' {
  declare module.exports: $Exports<'react-responsive-masonry/es/ResponsiveMasonry/index'>;
}
declare module 'react-responsive-masonry/lib/index.js' {
  declare module.exports: $Exports<'react-responsive-masonry/lib/index'>;
}
declare module 'react-responsive-masonry/lib/Masonry/index.js' {
  declare module.exports: $Exports<'react-responsive-masonry/lib/Masonry/index'>;
}
declare module 'react-responsive-masonry/lib/ResponsiveMasonry/index.js' {
  declare module.exports: $Exports<'react-responsive-masonry/lib/ResponsiveMasonry/index'>;
}
declare module 'react-responsive-masonry/umd/react-responsive-masonry.js' {
  declare module.exports: $Exports<'react-responsive-masonry/umd/react-responsive-masonry'>;
}
