// flow-typed signature: 8aa1ad5efb7fe8237de86f525f39f3bf
// flow-typed version: <<STUB>>/url-search-params-polyfill_v^2.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-search-params-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-search-params-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-search-params-polyfill/test/index.test' {
  declare module.exports: any;
}

declare module 'url-search-params-polyfill/test/partial-support.test' {
  declare module.exports: any;
}

declare module 'url-search-params-polyfill/test/USP-without-full-feature' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-search-params-polyfill/index' {
  declare module.exports: $Exports<'url-search-params-polyfill'>;
}
declare module 'url-search-params-polyfill/index.js' {
  declare module.exports: $Exports<'url-search-params-polyfill'>;
}
declare module 'url-search-params-polyfill/test/index.test.js' {
  declare module.exports: $Exports<'url-search-params-polyfill/test/index.test'>;
}
declare module 'url-search-params-polyfill/test/partial-support.test.js' {
  declare module.exports: $Exports<'url-search-params-polyfill/test/partial-support.test'>;
}
declare module 'url-search-params-polyfill/test/USP-without-full-feature.js' {
  declare module.exports: $Exports<'url-search-params-polyfill/test/USP-without-full-feature'>;
}
